### ISSUE TITLE
have_scheduled

### ISSUE THREAD

**Issue by andreacfm** [leshill/resque_spec#31]
I cannot make the have_scheduled matchers work.
Test case:

```
reminder:
  cron: 0 23 * * 1-5
  class: MyClass
  queue: my_quque
  description: ""
```

MyClass.perform does not take arguments.

Spec

```
it "should have scheduled the job" do   
  MyClass.should have_scheduled()     
end
```

I do not get what do I have to pass as argument. I tried anything and nothing looks correct.
Btw I can see that Resque.schedule has correctly scheduled the job.

Andrea
